#lang racket

(define (make-account balance password)
  (let ((pas-tries 0))
    (define (withdraw amount)
      (if (>= balance amount)
          (begin (set! balance (- balance amount))
                 balance)
          "Недостаточно средств на счёте"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (dispatch pas op)
      (if (eq? pas password)
          (begin (set! pas-tries 0)
                 (cond ((eq? op 'withdraw) withdraw)
                       ((eq? op 'deposit) deposit)
                       (else (lambda (x) "Такой операции не существует"))))
          (if (= pas-tries 6)
              (error "call-the-cops")
              (lambda (x) (begin (set! pas-tries (+ pas-tries 1)) "Неправильный пароль")))))
    dispatch))

(define acc (make-account 100 'secret-password))